@hostname = localhost:5000
@protocol = http
@baseURL = {{protocol}}://{{hostname}}

@authToken = {{login.response.headers.x-auth-token}}
GET {{baseURL}}/subscribers HTTP/1.1
x-auth-token: {{authToken}}

###
GET {{baseURL}}/subscribers/5f2d6f9e9322a27b0dc4d5fd HTTP/1.1
###
# @name login
POST {{baseURL}}/subscribers/ HTTP/1.1
content-type: application/json

{
    "name": "tester",
    "subscribedChannel": "john channel"
}

###
PATCH {{baseURL}}/subscribers/5f2d6f9e9322a27b0dc4d5fd HTTP/1.1
content-type: application/json

{
    "name": "sample2",
    "subscribedChannel": "john channel"
}

###
DELETE {{baseURL}}/subscribers/5f2d70519322a27b0dc4d5ff HTTP/1.1

###
POST {{baseURL}}/users/register
Content-Type: application/json

{
    "name": "armafe",
    "email": "testme2@gmail.com",
    "password": "abcdefg"
}

###
# @name login
POST {{baseURL}}/auth
Content-Type: application/json

{
    "email": "testme@gmail.com",
    "password": "abcdefg"
}

###
GET {{baseURL}}/products HTTP/1.1
###
POST {{baseURL}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "coke 1L my favorite"
}
###
DELETE {{baseURL}}/products/2 HTTP/1.1
###
PATCH {{baseURL}}/products/1
Content-Type: application/json

{
    "name": "changed to other name ",
    "description": "changed description"
}